package: accessdenied
version: '2.1.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/accessdenied
requires:
    packages:
        structure/content: '^2.1.0'
        yrewrite: '^2.6.0'
    redaxo: '^5.10.0'
    php:
        version: '>=7.4, <9'
    
conflicts:
    packages:
        locked: '>0.0.1'

page:
    hidden: true

pages: 
    system/accessdenied:    
        title: 'translate:accessdenied_title'
        icon: rex-icon fa-unlock-alt
        perm: admin

default_config:
    default_status: 0
    inherit: false
    linkparameter: 'preview'
