package: accessdenied
version: '1.0.6'
author: FriendsOfREDAXO
supportpage: github.com/FriendsOfREDAXO/accessdenied

requires:
    packages:
        structure: '^2.1.0'
    redaxo: '^5.1.0'
    php:
        version: '>=5.6'
