package: accessdenied
version: '1.1.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/accessdenied

requires:
    packages:
        structure: '^2.1.0'
    redaxo: '^5.1.0'
    php:
        version: '^7.0'

page:
    title: 'Artikelsperre'
    perm: admin

default_config:
    default_status: 0
