package: accessdenied
version: '1.0.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/accessdenied

requires:
    packages:
        structure: '^2.2.0'
    redaxo: '^5.3.0'
    php:
        version: '>=5.6'
