package: accessdenied
version: '1.1.1'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/accessdenied

requires:
    packages:
        structure: '^2.1.0'
    redaxo: '^5.1.0'
    php:
        version: '>=7.0,9'

page:
    title: 'translate:accessdenied_title'
    icon: rex-icon fa-unlock-alt
    perm: admin


default_config:
    default_status: 0
